[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1435481624",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14691#issuecomment-1435481624",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14691",
        "id": 1435481624,
        "node_id": "IC_kwDOCVq1mM5Vj7YY",
        "user": {
            "login": "stevenlix",
            "id": 38092805,
            "node_id": "MDQ6VXNlcjM4MDkyODA1",
            "avatar_url": "https://avatars.githubusercontent.com/u/38092805?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stevenlix",
            "html_url": "https://github.com/stevenlix",
            "followers_url": "https://api.github.com/users/stevenlix/followers",
            "following_url": "https://api.github.com/users/stevenlix/following{/other_user}",
            "gists_url": "https://api.github.com/users/stevenlix/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stevenlix/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stevenlix/subscriptions",
            "organizations_url": "https://api.github.com/users/stevenlix/orgs",
            "repos_url": "https://api.github.com/users/stevenlix/repos",
            "events_url": "https://api.github.com/users/stevenlix/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stevenlix/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-02-18T04:39:47Z",
        "updated_at": "2023-02-18T05:23:13Z",
        "author_association": "CONTRIBUTOR",
        "body": "Thanks for reporting the issue. I've reproduced the issue. It seems only happening for onnx opset16 and above. If the model is converted in opset15, the inference goes through.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1435481624/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1439209271",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14691#issuecomment-1439209271",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14691",
        "id": 1439209271,
        "node_id": "IC_kwDOCVq1mM5VyJc3",
        "user": {
            "login": "satyajandhyala",
            "id": 26722914,
            "node_id": "MDQ6VXNlcjI2NzIyOTE0",
            "avatar_url": "https://avatars.githubusercontent.com/u/26722914?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/satyajandhyala",
            "html_url": "https://github.com/satyajandhyala",
            "followers_url": "https://api.github.com/users/satyajandhyala/followers",
            "following_url": "https://api.github.com/users/satyajandhyala/following{/other_user}",
            "gists_url": "https://api.github.com/users/satyajandhyala/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/satyajandhyala/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/satyajandhyala/subscriptions",
            "organizations_url": "https://api.github.com/users/satyajandhyala/orgs",
            "repos_url": "https://api.github.com/users/satyajandhyala/repos",
            "events_url": "https://api.github.com/users/satyajandhyala/events{/privacy}",
            "received_events_url": "https://api.github.com/users/satyajandhyala/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-02-21T23:07:22Z",
        "updated_at": "2023-04-06T21:14:56Z",
        "author_association": "MEMBER",
        "body": "The RoiAlign opset 16 is not supported on CUDA EP currently. The fall back CPU EP appears to have an issue. If the loop is run only once the bug is not reproducible. If session.run is called twice then then bug is reproducible. For opset 16 the following additional operators (compared to opset 15) are assigned to CPU EP\r\nFlatten\r\nIdentity\r\nIf\r\nLoop\r\nRoiAlign\r\nScatterElements\r\nShape",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1439209271/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1538284649",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14691#issuecomment-1538284649",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14691",
        "id": 1538284649,
        "node_id": "IC_kwDOCVq1mM5bsFxp",
        "user": {
            "login": "Callidior",
            "id": 7915048,
            "node_id": "MDQ6VXNlcjc5MTUwNDg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/7915048?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Callidior",
            "html_url": "https://github.com/Callidior",
            "followers_url": "https://api.github.com/users/Callidior/followers",
            "following_url": "https://api.github.com/users/Callidior/following{/other_user}",
            "gists_url": "https://api.github.com/users/Callidior/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Callidior/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Callidior/subscriptions",
            "organizations_url": "https://api.github.com/users/Callidior/orgs",
            "repos_url": "https://api.github.com/users/Callidior/repos",
            "events_url": "https://api.github.com/users/Callidior/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Callidior/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-05-08T12:32:46Z",
        "updated_at": "2023-05-08T12:32:46Z",
        "author_association": "NONE",
        "body": "I think I encountered the same or at least a similar issue and wanted to share my code, since it is small and easy to reproduce.\r\n\r\nI export the following PyTorch model to ONNX:\r\n\r\n```python\r\nimport torch\r\nimport torch.nn.functional as F\r\nfrom torch import nn, Tensor\r\n\r\n\r\n@torch.jit.script_if_tracing\r\ndef nonzero_coords_padded(heatmap: Tensor) -> Tensor:\r\n\r\n    # Find nonzero points\r\n    points = [torch.nonzero(m) for m in heatmap]\r\n\r\n    # Create output tensors\r\n    max_num = 0\r\n    for c in points:\r\n        max_num = max(max_num, len(c))\r\n    det_points: Tensor = heatmap.new_full((len(points), max_num, 2), -1, dtype=torch.long)\r\n\r\n    for i, c in enumerate(points):\r\n        det_points[i, :c.size(0)] = c\r\n\r\n    return det_points\r\n\r\n\r\nclass Model(nn.Module):\r\n    def forward(self, x: Tensor) -> Tensor:\r\n        return nonzero_coords_padded(x)\r\n```\r\n\r\nWhen I run the ONNX model, I don't get a segfault but sometimes incorrect results. Even with the same input data, the result is sometimes correct, sometimes wrong. This can be worked around by downgrading ONNX runtime to <= 1.13 or exporting to opset < 16.\r\n\r\nMy test input is created as follows:\r\n\r\n```python\r\nimport numpy as np\r\n\r\ntrue_centers = [\r\n    [[127, 68], [99, 245]],\r\n    [[11, 197], [222, 33], [123, 231]]\r\n]\r\ntest_inputs = np.zeros((2, 256, 256), dtype=np.float32)\r\nfor i, tc in enumerate(true_centers):\r\n    test_inputs[i][tuple(np.asarray(tc).T)] = 1\r\n```\r\n\r\nThe correct model output looks as follows:\r\n\r\n```python\r\narray([[[ 99, 245],\r\n        [127,  68],\r\n        [ -1,  -1]],\r\n\r\n       [[ 11, 197],\r\n        [123, 231],\r\n        [222,  33]]], dtype=int64)\r\n```\r\n\r\nAbout 25% of the time, I get the following output instead:\r\n\r\n```python\r\narray([[[ 11, 197],\r\n        [123, 231],\r\n        [ -1,  -1]],\r\n\r\n       [[ 11, 197],\r\n        [123, 231],\r\n        [222,  33]]], dtype=int64)\r\n```\r\n\r\nHere, the difference is small. If my model and input data grow bigger, the output becomes complete rubbish.\r\n\r\nI suspect that the for loop is part of the issue. ",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1538284649/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1550054007",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14691#issuecomment-1550054007",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14691",
        "id": 1550054007,
        "node_id": "IC_kwDOCVq1mM5cY_J3",
        "user": {
            "login": "RandySheriffH",
            "id": 48490400,
            "node_id": "MDQ6VXNlcjQ4NDkwNDAw",
            "avatar_url": "https://avatars.githubusercontent.com/u/48490400?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/RandySheriffH",
            "html_url": "https://github.com/RandySheriffH",
            "followers_url": "https://api.github.com/users/RandySheriffH/followers",
            "following_url": "https://api.github.com/users/RandySheriffH/following{/other_user}",
            "gists_url": "https://api.github.com/users/RandySheriffH/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/RandySheriffH/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/RandySheriffH/subscriptions",
            "organizations_url": "https://api.github.com/users/RandySheriffH/orgs",
            "repos_url": "https://api.github.com/users/RandySheriffH/repos",
            "events_url": "https://api.github.com/users/RandySheriffH/events{/privacy}",
            "received_events_url": "https://api.github.com/users/RandySheriffH/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-05-16T17:06:54Z",
        "updated_at": "2023-05-16T17:08:01Z",
        "author_association": "MEMBER",
        "body": "@vahvero @Callidior : the fix's been merged - mind try building from the latest main for an update? ",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1550054007/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1550263791",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14691#issuecomment-1550263791",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14691",
        "id": 1550263791,
        "node_id": "IC_kwDOCVq1mM5cZyXv",
        "user": {
            "login": "vahvero",
            "id": 30704280,
            "node_id": "MDQ6VXNlcjMwNzA0Mjgw",
            "avatar_url": "https://avatars.githubusercontent.com/u/30704280?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vahvero",
            "html_url": "https://github.com/vahvero",
            "followers_url": "https://api.github.com/users/vahvero/followers",
            "following_url": "https://api.github.com/users/vahvero/following{/other_user}",
            "gists_url": "https://api.github.com/users/vahvero/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/vahvero/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/vahvero/subscriptions",
            "organizations_url": "https://api.github.com/users/vahvero/orgs",
            "repos_url": "https://api.github.com/users/vahvero/repos",
            "events_url": "https://api.github.com/users/vahvero/events{/privacy}",
            "received_events_url": "https://api.github.com/users/vahvero/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-05-16T19:44:38Z",
        "updated_at": "2023-05-16T19:44:38Z",
        "author_association": "NONE",
        "body": "I came up with some dependency issues when building from source. I can probably try with a deeper dive again later during the weekend. ",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1550263791/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1554191044",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14691#issuecomment-1554191044",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14691",
        "id": 1554191044,
        "node_id": "IC_kwDOCVq1mM5coxLE",
        "user": {
            "login": "Dexterp37",
            "id": 883721,
            "node_id": "MDQ6VXNlcjg4MzcyMQ==",
            "avatar_url": "https://avatars.githubusercontent.com/u/883721?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Dexterp37",
            "html_url": "https://github.com/Dexterp37",
            "followers_url": "https://api.github.com/users/Dexterp37/followers",
            "following_url": "https://api.github.com/users/Dexterp37/following{/other_user}",
            "gists_url": "https://api.github.com/users/Dexterp37/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Dexterp37/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Dexterp37/subscriptions",
            "organizations_url": "https://api.github.com/users/Dexterp37/orgs",
            "repos_url": "https://api.github.com/users/Dexterp37/repos",
            "events_url": "https://api.github.com/users/Dexterp37/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Dexterp37/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-05-19T07:57:39Z",
        "updated_at": "2023-05-19T07:57:39Z",
        "author_association": "NONE",
        "body": "> @vahvero @Callidior : the fix's been merged - mind try building from the latest main for an update?\r\n\r\nI can confirm that this fixes the segfault for me with the last `onnxruntime-gpu` Nightly on Windows (python).",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1554191044/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1555032524",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14691#issuecomment-1555032524",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14691",
        "id": 1555032524,
        "node_id": "IC_kwDOCVq1mM5cr-nM",
        "user": {
            "login": "RandySheriffH",
            "id": 48490400,
            "node_id": "MDQ6VXNlcjQ4NDkwNDAw",
            "avatar_url": "https://avatars.githubusercontent.com/u/48490400?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/RandySheriffH",
            "html_url": "https://github.com/RandySheriffH",
            "followers_url": "https://api.github.com/users/RandySheriffH/followers",
            "following_url": "https://api.github.com/users/RandySheriffH/following{/other_user}",
            "gists_url": "https://api.github.com/users/RandySheriffH/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/RandySheriffH/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/RandySheriffH/subscriptions",
            "organizations_url": "https://api.github.com/users/RandySheriffH/orgs",
            "repos_url": "https://api.github.com/users/RandySheriffH/repos",
            "events_url": "https://api.github.com/users/RandySheriffH/events{/privacy}",
            "received_events_url": "https://api.github.com/users/RandySheriffH/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-05-19T17:54:45Z",
        "updated_at": "2023-05-19T17:54:45Z",
        "author_association": "MEMBER",
        "body": "Thanks for the confirmation!\r\nClosing the issue but feel free to reach out for further assistance.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1555032524/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]