[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1301933501",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/13509#issuecomment-1301933501",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/13509",
        "id": 1301933501,
        "node_id": "IC_kwDOCVq1mM5Nme29",
        "user": {
            "login": "mszhanyi",
            "id": 16190118,
            "node_id": "MDQ6VXNlcjE2MTkwMTE4",
            "avatar_url": "https://avatars.githubusercontent.com/u/16190118?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mszhanyi",
            "html_url": "https://github.com/mszhanyi",
            "followers_url": "https://api.github.com/users/mszhanyi/followers",
            "following_url": "https://api.github.com/users/mszhanyi/following{/other_user}",
            "gists_url": "https://api.github.com/users/mszhanyi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mszhanyi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mszhanyi/subscriptions",
            "organizations_url": "https://api.github.com/users/mszhanyi/orgs",
            "repos_url": "https://api.github.com/users/mszhanyi/repos",
            "events_url": "https://api.github.com/users/mszhanyi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mszhanyi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-11-03T11:00:34Z",
        "updated_at": "2022-11-03T11:00:34Z",
        "author_association": "MEMBER",
        "body": "I tried debugging it.\r\n\r\n**The internal exception messages are**\r\n`Non-zero status code returned while running Resize node. Name:'Resize_156' Status Message: D:\\git\\onnxruntime\\onnxruntime\\core\\framework\\execution_frame.cc:161 onnxruntime::IExecutionFrame::GetOrCreateNodeOutputMLValue shape && tensor.Shape() == *shape was false. OrtValue shape verification failed. Current shape:{1,21,480,640} Requested shape:{1,21,478,640}`\r\n\r\n**While running with the second test data set,** \r\nTo WinML, the p_ort_value is allocated, but the tensor shape isn't matching the current request shape.\r\nTo onnxruntime_test_all, the p_ort_value isn't allocated, so it creates a new one, so there's no exception.\r\n**It looks there's something wrong with the deallocation in WinML.**\r\nhttps://github.com/microsoft/onnxruntime/blob/7c3a23c18600d6e2d0755b95e86e3a86bfad36ac/onnxruntime/core/framework/execution_frame.cc#L155-L175\r\n\r\ncc @snnn",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1301933501/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1302732658",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/13509#issuecomment-1302732658",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/13509",
        "id": 1302732658,
        "node_id": "IC_kwDOCVq1mM5Nph9y",
        "user": {
            "login": "snnn",
            "id": 856316,
            "node_id": "MDQ6VXNlcjg1NjMxNg==",
            "avatar_url": "https://avatars.githubusercontent.com/u/856316?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/snnn",
            "html_url": "https://github.com/snnn",
            "followers_url": "https://api.github.com/users/snnn/followers",
            "following_url": "https://api.github.com/users/snnn/following{/other_user}",
            "gists_url": "https://api.github.com/users/snnn/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/snnn/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/snnn/subscriptions",
            "organizations_url": "https://api.github.com/users/snnn/orgs",
            "repos_url": "https://api.github.com/users/snnn/repos",
            "events_url": "https://api.github.com/users/snnn/events{/privacy}",
            "received_events_url": "https://api.github.com/users/snnn/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-11-03T22:11:51Z",
        "updated_at": "2022-11-03T22:11:51Z",
        "author_association": "MEMBER",
        "body": "You mean the shape provided by the model is wrong? If that, we should ask them to update the model.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1302732658/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]