[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1352850195",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/13975#issuecomment-1352850195",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/13975",
        "id": 1352850195,
        "node_id": "IC_kwDOCVq1mM5QotsT",
        "user": {
            "login": "adepierre",
            "id": 24371370,
            "node_id": "MDQ6VXNlcjI0MzcxMzcw",
            "avatar_url": "https://avatars.githubusercontent.com/u/24371370?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/adepierre",
            "html_url": "https://github.com/adepierre",
            "followers_url": "https://api.github.com/users/adepierre/followers",
            "following_url": "https://api.github.com/users/adepierre/following{/other_user}",
            "gists_url": "https://api.github.com/users/adepierre/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/adepierre/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/adepierre/subscriptions",
            "organizations_url": "https://api.github.com/users/adepierre/orgs",
            "repos_url": "https://api.github.com/users/adepierre/repos",
            "events_url": "https://api.github.com/users/adepierre/events{/privacy}",
            "received_events_url": "https://api.github.com/users/adepierre/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-12-15T10:22:39Z",
        "updated_at": "2022-12-15T10:34:28Z",
        "author_association": "NONE",
        "body": "Quick update : I tried to replace the Resize op doing a quick \"custom nearest interpolate function\", but it leads to a similar issue, this time with Concat node üôÅ\r\nI think the root cause might be the dynamic size of the input, but I don't really know how to investigate more the issue and even less fix it\r\n\r\n```python\r\nimport torch\r\n\r\ndef resize(x: torch.Tensor, scale_factor:int):\r\n    stacked_h = torch.stack([x]*scale_factor, dim=-1).view(*x.shape[:-1], scale_factor*x.shape[-1])\r\n    stacked = torch.stack([stacked_h]*scale_factor, dim=-2).view(*x.shape[:-2], scale_factor*x.shape[-2], scale_factor*x.shape[-1])\r\n\r\n    return stacked\r\n\r\nclass TestModel(torch.nn.Module):\r\n    def forward(self, x):\r\n        return resize(x, scale_factor=2)\r\n\r\nmodel = TestModel()\r\nexample = torch.rand(1, 3, 256, 256)\r\ntorch.onnx.export(model,\r\n                    example,\r\n                    'test.onnx',\r\n                    input_names=['inputs'],\r\n                    export_params=True,\r\n                    dynamic_axes={'inputs': {2 : 'height', 3: 'width'}}\r\n)\r\n```\r\n\r\n```\r\n[E:onnxruntime:, sequential_executor.cc:369 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Concat node. Name:'Concat_4' Status Message: D:\\a\\_work\\1\\s\\onnxruntime\\core\\providers\\dml\\DmlExecutionProvider\\src\\MLOperatorAuthorImpl.cpp(1866)\\onnxruntime.dll\r\n```",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1352850195/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1512903200",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/13975#issuecomment-1512903200",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/13975",
        "id": 1512903200,
        "node_id": "IC_kwDOCVq1mM5aLRIg",
        "user": {
            "login": "VladMVLX",
            "id": 58504993,
            "node_id": "MDQ6VXNlcjU4NTA0OTkz",
            "avatar_url": "https://avatars.githubusercontent.com/u/58504993?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/VladMVLX",
            "html_url": "https://github.com/VladMVLX",
            "followers_url": "https://api.github.com/users/VladMVLX/followers",
            "following_url": "https://api.github.com/users/VladMVLX/following{/other_user}",
            "gists_url": "https://api.github.com/users/VladMVLX/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/VladMVLX/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/VladMVLX/subscriptions",
            "organizations_url": "https://api.github.com/users/VladMVLX/orgs",
            "repos_url": "https://api.github.com/users/VladMVLX/repos",
            "events_url": "https://api.github.com/users/VladMVLX/events{/privacy}",
            "received_events_url": "https://api.github.com/users/VladMVLX/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-04-18T11:20:08Z",
        "updated_at": "2023-04-18T11:20:08Z",
        "author_association": "NONE",
        "body": "Unfortunately having the same problem now in April 2023 :(",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1512903200/reactions",
            "total_count": 1,
            "+1": 1,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]