[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1160153239",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11241#issuecomment-1160153239",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11241",
        "id": 1160153239,
        "node_id": "IC_kwDOCVq1mM5FJoiX",
        "user": {
            "login": "Jinming-Su",
            "id": 16068384,
            "node_id": "MDQ6VXNlcjE2MDY4Mzg0",
            "avatar_url": "https://avatars.githubusercontent.com/u/16068384?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Jinming-Su",
            "html_url": "https://github.com/Jinming-Su",
            "followers_url": "https://api.github.com/users/Jinming-Su/followers",
            "following_url": "https://api.github.com/users/Jinming-Su/following{/other_user}",
            "gists_url": "https://api.github.com/users/Jinming-Su/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Jinming-Su/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Jinming-Su/subscriptions",
            "organizations_url": "https://api.github.com/users/Jinming-Su/orgs",
            "repos_url": "https://api.github.com/users/Jinming-Su/repos",
            "events_url": "https://api.github.com/users/Jinming-Su/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Jinming-Su/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-20T08:43:46Z",
        "updated_at": "2022-06-20T08:44:05Z",
        "author_association": "NONE",
        "body": "I happen the same problem. Have you solved this?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1160153239/reactions",
            "total_count": 1,
            "+1": 1,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1193637824",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11241#issuecomment-1193637824",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11241",
        "id": 1193637824,
        "node_id": "IC_kwDOCVq1mM5HJXfA",
        "user": {
            "login": "k2m5t2",
            "id": 57116824,
            "node_id": "MDQ6VXNlcjU3MTE2ODI0",
            "avatar_url": "https://avatars.githubusercontent.com/u/57116824?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/k2m5t2",
            "html_url": "https://github.com/k2m5t2",
            "followers_url": "https://api.github.com/users/k2m5t2/followers",
            "following_url": "https://api.github.com/users/k2m5t2/following{/other_user}",
            "gists_url": "https://api.github.com/users/k2m5t2/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/k2m5t2/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/k2m5t2/subscriptions",
            "organizations_url": "https://api.github.com/users/k2m5t2/orgs",
            "repos_url": "https://api.github.com/users/k2m5t2/repos",
            "events_url": "https://api.github.com/users/k2m5t2/events{/privacy}",
            "received_events_url": "https://api.github.com/users/k2m5t2/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-07-25T06:31:25Z",
        "updated_at": "2022-07-25T06:31:25Z",
        "author_association": "NONE",
        "body": "Encountered the same problem while converting PiDiNet into ONNX. ",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1193637824/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1193995331",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11241#issuecomment-1193995331",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11241",
        "id": 1193995331,
        "node_id": "IC_kwDOCVq1mM5HKuxD",
        "user": {
            "login": "EdVince",
            "id": 18224516,
            "node_id": "MDQ6VXNlcjE4MjI0NTE2",
            "avatar_url": "https://avatars.githubusercontent.com/u/18224516?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/EdVince",
            "html_url": "https://github.com/EdVince",
            "followers_url": "https://api.github.com/users/EdVince/followers",
            "following_url": "https://api.github.com/users/EdVince/following{/other_user}",
            "gists_url": "https://api.github.com/users/EdVince/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/EdVince/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/EdVince/subscriptions",
            "organizations_url": "https://api.github.com/users/EdVince/orgs",
            "repos_url": "https://api.github.com/users/EdVince/repos",
            "events_url": "https://api.github.com/users/EdVince/events{/privacy}",
            "received_events_url": "https://api.github.com/users/EdVince/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-07-25T12:37:45Z",
        "updated_at": "2022-07-25T12:38:16Z",
        "author_association": "NONE",
        "body": "I think the error message tells us everything. The error message tells us that it happened \"while running FusedConv node\" and the error is \"bias should be 1D\". In this graph, it may not be obvious that in the \"Add\" operator it is actually a bias computation, from “FusedConv” , we can know that onnxruntime is trying to fuse the graph, so it is easy to know that it is trying to fuse bias and conv together, which is a very common graph optimization operation. But in the traditional sense of fusing bias and conv, the bias here is actually a 1D data, which should come from Conv, for example, torch.Conv2D(bias=True) the bias generated here. But in this graph, the bias here is in fact a 4D data, which is actually not the true bias with conv. So the solution is simple, since it appears in the \"FusedConv\" process, as long as we don't fuse it, we won't report an error. By consulting onnxruntime's [doc](https://onnxruntime.ai/docs/performance/graph-optimizations.html) we can simply add a few lines of code that will disable the fusion and make it work successfully:\r\n\r\n```\r\nsess_options = ort.SessionOptions()\r\nsess_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_BASIC\r\nmodel = ort.InferenceSession(onnx_path, sess_options=sess_options, providers=providers)\r\n```\r\n\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1193995331/reactions",
            "total_count": 10,
            "+1": 6,
            "-1": 0,
            "laugh": 1,
            "hooray": 1,
            "confused": 0,
            "heart": 0,
            "rocket": 1,
            "eyes": 1
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1471525648",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11241#issuecomment-1471525648",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11241",
        "id": 1471525648,
        "node_id": "IC_kwDOCVq1mM5XtbMQ",
        "user": {
            "login": "SinnCyann",
            "id": 30388850,
            "node_id": "MDQ6VXNlcjMwMzg4ODUw",
            "avatar_url": "https://avatars.githubusercontent.com/u/30388850?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SinnCyann",
            "html_url": "https://github.com/SinnCyann",
            "followers_url": "https://api.github.com/users/SinnCyann/followers",
            "following_url": "https://api.github.com/users/SinnCyann/following{/other_user}",
            "gists_url": "https://api.github.com/users/SinnCyann/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SinnCyann/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SinnCyann/subscriptions",
            "organizations_url": "https://api.github.com/users/SinnCyann/orgs",
            "repos_url": "https://api.github.com/users/SinnCyann/repos",
            "events_url": "https://api.github.com/users/SinnCyann/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SinnCyann/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-03-16T08:37:55Z",
        "updated_at": "2023-03-16T08:37:55Z",
        "author_association": "NONE",
        "body": "> I happen the same problem. Have you solved this?\r\n\r\nadd bias in Conv at the original model  can solve this problem.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1471525648/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]