[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1285388931",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/13383#issuecomment-1285388931",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/13383",
        "id": 1285388931,
        "node_id": "IC_kwDOCVq1mM5MnXqD",
        "user": {
            "login": "josephrocca",
            "id": 1167575,
            "node_id": "MDQ6VXNlcjExNjc1NzU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1167575?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/josephrocca",
            "html_url": "https://github.com/josephrocca",
            "followers_url": "https://api.github.com/users/josephrocca/followers",
            "following_url": "https://api.github.com/users/josephrocca/following{/other_user}",
            "gists_url": "https://api.github.com/users/josephrocca/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/josephrocca/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/josephrocca/subscriptions",
            "organizations_url": "https://api.github.com/users/josephrocca/orgs",
            "repos_url": "https://api.github.com/users/josephrocca/repos",
            "events_url": "https://api.github.com/users/josephrocca/events{/privacy}",
            "received_events_url": "https://api.github.com/users/josephrocca/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-10-20T11:48:03Z",
        "updated_at": "2022-10-20T11:48:03Z",
        "author_association": "CONTRIBUTOR",
        "body": "I'm wondering if it's possible for a \"debug\" build to be published which makes error messages like this more informative? Just something like:\r\n```\r\nhttps://cdn.jsdelivr.net/npm/onnxruntime-web@1.12.1/dist/ort-debug.js\r\n```\r\nso it's easy to switch in and out of debug mode. That is, assuming it's possible to configure build flags to make error messages like these more informative.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1285388931/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1286281446",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/13383#issuecomment-1286281446",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/13383",
        "id": 1286281446,
        "node_id": "IC_kwDOCVq1mM5Mqxjm",
        "user": {
            "login": "shalvamist",
            "id": 94086448,
            "node_id": "U_kgDOBZulMA",
            "avatar_url": "https://avatars.githubusercontent.com/u/94086448?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/shalvamist",
            "html_url": "https://github.com/shalvamist",
            "followers_url": "https://api.github.com/users/shalvamist/followers",
            "following_url": "https://api.github.com/users/shalvamist/following{/other_user}",
            "gists_url": "https://api.github.com/users/shalvamist/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/shalvamist/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/shalvamist/subscriptions",
            "organizations_url": "https://api.github.com/users/shalvamist/orgs",
            "repos_url": "https://api.github.com/users/shalvamist/repos",
            "events_url": "https://api.github.com/users/shalvamist/events{/privacy}",
            "received_events_url": "https://api.github.com/users/shalvamist/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-10-20T23:45:47Z",
        "updated_at": "2022-10-20T23:46:29Z",
        "author_association": "MEMBER",
        "body": "Hey @josephrocca,\r\n\r\nThanks for reporting the issue in such detail.\r\nI was able to reproduce the issue on my side - I will investigate the problem and update you with my findings.\r\n\r\nBTW, regarding this debug build - I will see what we can do. In the meanwhile just FYI we are working on simplifying the ORT Web build process. But please refer to [ORT Web build instructions](https://onnxruntime.ai/docs/build/web.html)",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1286281446/reactions",
            "total_count": 1,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 1,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1287768784",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/13383#issuecomment-1287768784",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/13383",
        "id": 1287768784,
        "node_id": "IC_kwDOCVq1mM5MwcrQ",
        "user": {
            "login": "iishiishii",
            "id": 59903692,
            "node_id": "MDQ6VXNlcjU5OTAzNjky",
            "avatar_url": "https://avatars.githubusercontent.com/u/59903692?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/iishiishii",
            "html_url": "https://github.com/iishiishii",
            "followers_url": "https://api.github.com/users/iishiishii/followers",
            "following_url": "https://api.github.com/users/iishiishii/following{/other_user}",
            "gists_url": "https://api.github.com/users/iishiishii/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/iishiishii/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/iishiishii/subscriptions",
            "organizations_url": "https://api.github.com/users/iishiishii/orgs",
            "repos_url": "https://api.github.com/users/iishiishii/repos",
            "events_url": "https://api.github.com/users/iishiishii/events{/privacy}",
            "received_events_url": "https://api.github.com/users/iishiishii/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-10-22T11:39:53Z",
        "updated_at": "2022-10-24T09:04:40Z",
        "author_association": "NONE",
        "body": "I got similar error. The session was created but failed to run for [this model](https://huggingface.co/iishiishii/brain_mask/resolve/main/model.onnx) with onnxruntime-web. The inference in python works just fine.\r\nWhen I paused on promise rejection, it was caught on ort-wasm-threaded.min.js\r\n\r\n```\r\n    Te  @  ort-wasm-threaded.min.js:1 \r\n    nt  @  ort-wasm-threaded.min.js:1 \r\n    $func3851  @  ort-wasm-simd-threaded.wasm:0x2de185\r\n    $func1799  @  ort-wasm-simd-threaded.wasm:0x12f602\r\n    $func499  @  ort-wasm-simd-threaded.wasm:0x3c91b\r\n    $func3798  @  ort-wasm-simd-threaded.wasm:0x2d8b21\r\n    $func460  @  ort-wasm-simd-threaded.wasm:0x38d0a \r\n    $func54  @  ort-wasm-simd-threaded.wasm:0x85dd \r\n    $func5149  @  ort-wasm-simd-threaded.wasm:0x3ca275\r\n    $func96  @  ort-wasm-simd-threaded.wasm:0xbde9 \r\n    $func9574  @  ort-wasm-simd-threaded.wasm:0x6b1386\r\n    $func1033  @  ort-wasm-simd-threaded.wasm:0x97f54\r\n    $func1319  @  ort-wasm-simd-threaded.wasm:0xce862\r\n    $func5229  @  ort-wasm-simd-threaded.wasm:0x3d4b0a \r\n    $ra  @  ort-wasm-simd-threaded.wasm:0x473c81 \r\n    t.run  @  wasm-core-impl.ts:311\r\n    t.run  @  proxy-wrapper.ts:168\r\n    run  @  session-handler.ts:73 \r\n    run  @  inference-session-impl.ts:108 \r\n    (anonymous)  @  inference.js:149 \r\n    Promise.then (async)       \r\n    lm_inference  @  inference.js:149\r\n```\r\n\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1287768784/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1287867799",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/13383#issuecomment-1287867799",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/13383",
        "id": 1287867799,
        "node_id": "IC_kwDOCVq1mM5Mw02X",
        "user": {
            "login": "abb128",
            "id": 65567823,
            "node_id": "MDQ6VXNlcjY1NTY3ODIz",
            "avatar_url": "https://avatars.githubusercontent.com/u/65567823?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/abb128",
            "html_url": "https://github.com/abb128",
            "followers_url": "https://api.github.com/users/abb128/followers",
            "following_url": "https://api.github.com/users/abb128/following{/other_user}",
            "gists_url": "https://api.github.com/users/abb128/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/abb128/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/abb128/subscriptions",
            "organizations_url": "https://api.github.com/users/abb128/orgs",
            "repos_url": "https://api.github.com/users/abb128/repos",
            "events_url": "https://api.github.com/users/abb128/events{/privacy}",
            "received_events_url": "https://api.github.com/users/abb128/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-10-22T17:45:13Z",
        "updated_at": "2022-10-22T17:45:13Z",
        "author_association": "NONE",
        "body": "I'm getting a similar error with my own models. Two of my models are working fine, but the third one logs an error like this with a random number each time, regardless of what inputs I give it.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1287867799/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1295628054",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/13383#issuecomment-1295628054",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/13383",
        "id": 1295628054,
        "node_id": "IC_kwDOCVq1mM5NObcW",
        "user": {
            "login": "shalvamist",
            "id": 94086448,
            "node_id": "U_kgDOBZulMA",
            "avatar_url": "https://avatars.githubusercontent.com/u/94086448?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/shalvamist",
            "html_url": "https://github.com/shalvamist",
            "followers_url": "https://api.github.com/users/shalvamist/followers",
            "following_url": "https://api.github.com/users/shalvamist/following{/other_user}",
            "gists_url": "https://api.github.com/users/shalvamist/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/shalvamist/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/shalvamist/subscriptions",
            "organizations_url": "https://api.github.com/users/shalvamist/orgs",
            "repos_url": "https://api.github.com/users/shalvamist/repos",
            "events_url": "https://api.github.com/users/shalvamist/events{/privacy}",
            "received_events_url": "https://api.github.com/users/shalvamist/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-10-28T23:12:27Z",
        "updated_at": "2022-10-28T23:12:27Z",
        "author_association": "MEMBER",
        "body": "Hey Everyone,\r\n\r\nSorry for the delay in response. We have some progress on the issue - I was able to find that the model might has issues to run with ORT. here is the error - \r\n\r\n> onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'streamable_model_12/first_layerconv/conv1d_36/BiasAdd;streamable_model_12/first_layerconv/conv1d_36/Conv1D/Squeeze;streamable_model_12/first_layerconv/conv1d_36/BiasAdd/ReadVariableOp;Conv1D;streamable_model_12/first_layerconv/conv1d_36/Conv1D__39' Status Message: D:\\a\\_work\\1\\s\\onnxruntime\\core\\providers\\cpu\\tensor\\reshape_helper.h:41 onnxruntime::ReshapeHelper::ReshapeHelper gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,320,1}, requested shape:{1,1,1,368}\r\n\r\nThere might be an issue with the conversion - @josephrocca, where you able to run the model on ORT without ORT Web?\r\nI am continuing to debug the issue but if you have a working set up it will help to isolate the problem.\r\n\r\nIn regards of the broader issue of exception handling, we are aware of the limited debugging capabilities with the current build, and we are examining different ways to address the problem. Right now, we know how to retrieve the debug messages, but it requires a re-build. Our team is looking at a few option that might resolve the problem and how enable exception throwing will impact ORT Web. I will update soon with the decision - and I will also update (https://github.com/microsoft/onnxruntime/issues/13408).\r\n\r\nThanks",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1295628054/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1296302117",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/13383#issuecomment-1296302117",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/13383",
        "id": 1296302117,
        "node_id": "IC_kwDOCVq1mM5NRAAl",
        "user": {
            "login": "josephrocca",
            "id": 1167575,
            "node_id": "MDQ6VXNlcjExNjc1NzU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1167575?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/josephrocca",
            "html_url": "https://github.com/josephrocca",
            "followers_url": "https://api.github.com/users/josephrocca/followers",
            "following_url": "https://api.github.com/users/josephrocca/following{/other_user}",
            "gists_url": "https://api.github.com/users/josephrocca/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/josephrocca/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/josephrocca/subscriptions",
            "organizations_url": "https://api.github.com/users/josephrocca/orgs",
            "repos_url": "https://api.github.com/users/josephrocca/repos",
            "events_url": "https://api.github.com/users/josephrocca/events{/privacy}",
            "received_events_url": "https://api.github.com/users/josephrocca/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-10-30T16:59:01Z",
        "updated_at": "2022-10-30T16:59:01Z",
        "author_association": "CONTRIBUTOR",
        "body": "Hi @shalvamist, I've just tested it and am seeing the same error in ORT Python. Here's a minimal reproduction:\r\n\r\nhttps://colab.research.google.com/gist/josephrocca/91e876fd90e6b7c88429258ba2384a36/onnx-runtime-python-inference.ipynb\r\n\r\nBut I think the particular problem in my case may be due to a tf2onnx conversion issue. Please see [this comment](https://github.com/onnx/tensorflow-onnx/issues/2059#issuecomment-1296301499) and the ones above it for more context.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1296302117/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1297834918",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/13383#issuecomment-1297834918",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/13383",
        "id": 1297834918,
        "node_id": "IC_kwDOCVq1mM5NW2Om",
        "user": {
            "login": "shalvamist",
            "id": 94086448,
            "node_id": "U_kgDOBZulMA",
            "avatar_url": "https://avatars.githubusercontent.com/u/94086448?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/shalvamist",
            "html_url": "https://github.com/shalvamist",
            "followers_url": "https://api.github.com/users/shalvamist/followers",
            "following_url": "https://api.github.com/users/shalvamist/following{/other_user}",
            "gists_url": "https://api.github.com/users/shalvamist/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/shalvamist/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/shalvamist/subscriptions",
            "organizations_url": "https://api.github.com/users/shalvamist/orgs",
            "repos_url": "https://api.github.com/users/shalvamist/repos",
            "events_url": "https://api.github.com/users/shalvamist/events{/privacy}",
            "received_events_url": "https://api.github.com/users/shalvamist/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-11-01T00:04:38Z",
        "updated_at": "2022-11-01T00:04:38Z",
        "author_association": "MEMBER",
        "body": "Hi @josephrocca,\r\n\r\nThanks for sharing the colab, this aligns with my findings. (The errors match)\r\nSince you already have an ongoing discussion on the conversion it seems like the right place to resolve the issue.\r\nI will update this thread with the upcoming PR regarding exception handling. Please let me know if you need anything else related to the issue or ORT Web.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1297834918/reactions",
            "total_count": 1,
            "+1": 1,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1303282540",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/13383#issuecomment-1303282540",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/13383",
        "id": 1303282540,
        "node_id": "IC_kwDOCVq1mM5NroNs",
        "user": {
            "login": "josephrocca",
            "id": 1167575,
            "node_id": "MDQ6VXNlcjExNjc1NzU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1167575?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/josephrocca",
            "html_url": "https://github.com/josephrocca",
            "followers_url": "https://api.github.com/users/josephrocca/followers",
            "following_url": "https://api.github.com/users/josephrocca/following{/other_user}",
            "gists_url": "https://api.github.com/users/josephrocca/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/josephrocca/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/josephrocca/subscriptions",
            "organizations_url": "https://api.github.com/users/josephrocca/orgs",
            "repos_url": "https://api.github.com/users/josephrocca/repos",
            "events_url": "https://api.github.com/users/josephrocca/events{/privacy}",
            "received_events_url": "https://api.github.com/users/josephrocca/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-11-04T11:15:41Z",
        "updated_at": "2022-11-04T11:15:41Z",
        "author_association": "CONTRIBUTOR",
        "body": "Thanks @shalvamist - the other commenters likely having different issues so I'm reluctant to close, but I think this is best tracked at #13408? I'll close it and let you re-open if needed.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1303282540/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]