[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/816762851",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/7300#issuecomment-816762851",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/7300",
        "id": 816762851,
        "node_id": "MDEyOklzc3VlQ29tbWVudDgxNjc2Mjg1MQ==",
        "user": {
            "login": "tobigue",
            "id": 1560152,
            "node_id": "MDQ6VXNlcjE1NjAxNTI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1560152?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/tobigue",
            "html_url": "https://github.com/tobigue",
            "followers_url": "https://api.github.com/users/tobigue/followers",
            "following_url": "https://api.github.com/users/tobigue/following{/other_user}",
            "gists_url": "https://api.github.com/users/tobigue/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/tobigue/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/tobigue/subscriptions",
            "organizations_url": "https://api.github.com/users/tobigue/orgs",
            "repos_url": "https://api.github.com/users/tobigue/repos",
            "events_url": "https://api.github.com/users/tobigue/events{/privacy}",
            "received_events_url": "https://api.github.com/users/tobigue/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-04-09T15:26:27Z",
        "updated_at": "2021-04-09T16:43:57Z",
        "author_association": "NONE",
        "body": "I'm facing a similar issue. My model can be quantized and used fine with `1.6.0`, but fails with `1.7.0`.\r\n\r\nI'm quantizing the model successfully under `1.6.0` like this:\r\n```\r\nquantize_dynamic(\r\n    model_input=model_name,\r\n    model_output=output_model_name,\r\n    per_channel=True,\r\n    activation_type=QuantType.QUInt8,\r\n    weight_type=QuantType.QUInt8,\r\n)\r\n```\r\n\r\nWhen using `1.7.0` I have to set either `optimize_model=False` or `use_external_data_format=True`, as the constant folding optimiziation will result in a model >2GB (because it duplicates the embedding matrix) which leads to a `InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Protobuf serialization failed.` when quantizing. This is no problem, but:\r\n\r\nHowever, creating an `InferenceSession` for a model produced under `1.7.0` (with either of these options) results in this error:\r\n\r\n```\r\nenv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py in __init__(self, path_or_bytes, sess_options, providers, provider_options)\r\n    278 \r\n    279         try:\r\n--> 280             self._create_inference_session(providers, provider_options)\r\n    281         except RuntimeError:\r\n    282             if self._enable_fallback:\r\n\r\nenv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py in _create_inference_session(self, providers, provider_options)\r\n    305         session_options = self._sess_options if self._sess_options else C.get_default_session_options()\r\n    306         if self._model_path:\r\n--> 307             sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)\r\n    308         else:\r\n    309             sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)\r\n\r\nFail: [ONNXRuntimeError] : 1 : FAIL : Load model from models/mbart-large-en-ro/decoder-quantized/model.onnx failed:This is an invalid model. Error: Duplicate definition of name (decoder.embed_tokens.weight).\r\n```\r\n\r\nYou can download the onnx model before and after quantization [here](https://drive.google.com/file/d/15a3LTEZEG-QjIFK30iN0vejQg_VgMvQI/view?usp=sharing).\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/816762851/reactions",
            "total_count": 1,
            "+1": 1,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/827049369",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/7300#issuecomment-827049369",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/7300",
        "id": 827049369,
        "node_id": "MDEyOklzc3VlQ29tbWVudDgyNzA0OTM2OQ==",
        "user": {
            "login": "goksinan",
            "id": 36628896,
            "node_id": "MDQ6VXNlcjM2NjI4ODk2",
            "avatar_url": "https://avatars.githubusercontent.com/u/36628896?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/goksinan",
            "html_url": "https://github.com/goksinan",
            "followers_url": "https://api.github.com/users/goksinan/followers",
            "following_url": "https://api.github.com/users/goksinan/following{/other_user}",
            "gists_url": "https://api.github.com/users/goksinan/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/goksinan/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/goksinan/subscriptions",
            "organizations_url": "https://api.github.com/users/goksinan/orgs",
            "repos_url": "https://api.github.com/users/goksinan/repos",
            "events_url": "https://api.github.com/users/goksinan/events{/privacy}",
            "received_events_url": "https://api.github.com/users/goksinan/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-04-26T18:19:54Z",
        "updated_at": "2021-04-26T18:53:41Z",
        "author_association": "NONE",
        "body": "Similar issue here. Trying to quantize a FasterRCNN model exported from PyTorch. Quantized model is generated successfully, and the model size is reduced ~4X. But when I try to create an InferenceSession using onnxruntime, I get the following error:\r\n`onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from faster_rcnn_mobilenet_quantized.onnx failed:This is an invalid model. Error: two nodes with same node name (rpn.head.conv.bias_scale_node).`\r\nI wanted to exclude that node during quantization, but I don't know how to specify node names that `quantize_dynamic()` expects.\r\ntorch                1.8.1+cu102\r\nonnx                 1.8.1\r\nonnxruntime-noopenmp      1.6.0\r\nTo download: models [before](https://drive.google.com/file/d/1Qf3inzhhfEAjXxbY3BmP4lT3OuooVRFI/view?usp=sharing) and [after](https://drive.google.com/file/d/10oOwRwL3DWMyF3AJrC_YikTnFOOGDTOw/view?usp=sharing) quantization",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/827049369/reactions",
            "total_count": 1,
            "+1": 1,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/827053790",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/7300#issuecomment-827053790",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/7300",
        "id": 827053790,
        "node_id": "MDEyOklzc3VlQ29tbWVudDgyNzA1Mzc5MA==",
        "user": {
            "login": "yufenglee",
            "id": 30486710,
            "node_id": "MDQ6VXNlcjMwNDg2NzEw",
            "avatar_url": "https://avatars.githubusercontent.com/u/30486710?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yufenglee",
            "html_url": "https://github.com/yufenglee",
            "followers_url": "https://api.github.com/users/yufenglee/followers",
            "following_url": "https://api.github.com/users/yufenglee/following{/other_user}",
            "gists_url": "https://api.github.com/users/yufenglee/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yufenglee/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yufenglee/subscriptions",
            "organizations_url": "https://api.github.com/users/yufenglee/orgs",
            "repos_url": "https://api.github.com/users/yufenglee/repos",
            "events_url": "https://api.github.com/users/yufenglee/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yufenglee/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-04-26T18:27:17Z",
        "updated_at": "2021-04-26T18:27:17Z",
        "author_association": "MEMBER",
        "body": "@goksinan , i'm fixing the issue. Could you please also share you model?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/827053790/reactions",
            "total_count": 1,
            "+1": 1,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/899112246",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/7300#issuecomment-899112246",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/7300",
        "id": 899112246,
        "node_id": "IC_kwDOCVq1mM41l102",
        "user": {
            "login": "aescart1",
            "id": 1282924,
            "node_id": "MDQ6VXNlcjEyODI5MjQ=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1282924?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/aescart1",
            "html_url": "https://github.com/aescart1",
            "followers_url": "https://api.github.com/users/aescart1/followers",
            "following_url": "https://api.github.com/users/aescart1/following{/other_user}",
            "gists_url": "https://api.github.com/users/aescart1/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/aescart1/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/aescart1/subscriptions",
            "organizations_url": "https://api.github.com/users/aescart1/orgs",
            "repos_url": "https://api.github.com/users/aescart1/repos",
            "events_url": "https://api.github.com/users/aescart1/events{/privacy}",
            "received_events_url": "https://api.github.com/users/aescart1/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-08-15T21:29:06Z",
        "updated_at": "2021-08-15T21:29:06Z",
        "author_association": "NONE",
        "body": "> @goksinan , i'm fixing the issue. Could you please also share you model?\r\n\r\n@yufenglee  Hi, is it fixed ? As I still reproduce it. I know it's closed but thanks for your feedback",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/899112246/reactions",
            "total_count": 1,
            "+1": 1,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1397871059",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/7300#issuecomment-1397871059",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/7300",
        "id": 1397871059,
        "node_id": "IC_kwDOCVq1mM5TUdHT",
        "user": {
            "login": "nightflight-dk",
            "id": 9641988,
            "node_id": "MDQ6VXNlcjk2NDE5ODg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/9641988?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/nightflight-dk",
            "html_url": "https://github.com/nightflight-dk",
            "followers_url": "https://api.github.com/users/nightflight-dk/followers",
            "following_url": "https://api.github.com/users/nightflight-dk/following{/other_user}",
            "gists_url": "https://api.github.com/users/nightflight-dk/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/nightflight-dk/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/nightflight-dk/subscriptions",
            "organizations_url": "https://api.github.com/users/nightflight-dk/orgs",
            "repos_url": "https://api.github.com/users/nightflight-dk/repos",
            "events_url": "https://api.github.com/users/nightflight-dk/events{/privacy}",
            "received_events_url": "https://api.github.com/users/nightflight-dk/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-01-20T03:06:49Z",
        "updated_at": "2023-01-20T03:09:00Z",
        "author_association": "NONE",
        "body": "@yufenglee I can reproduce this as well. ORT-GPU 1.13.1  \r\n\r\n(Roberta-large)\r\nFail: [ONNXRuntimeError] : 1 : FAIL : Load model from quantized/model_quantized.onnx failed:This is an invalid model. Error: two nodes with same node name (/roberta/embeddings/LayerNorm/Add_1_output_0_QuantizeLinear).\r\n \r\n(deberta-large-mnli)\r\nFail: [ONNXRuntimeError] : 1 : FAIL : Load model from quantized/model_quantized_infs.onnx failed:This is an invalid model. Error: two nodes with same node name (/deberta/encoder/layer.0/attention/self/Div_1_output_0_QuantizeLinear).\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1397871059/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]