[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1639131707",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/16704#issuecomment-1639131707",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/16704",
        "id": 1639131707,
        "node_id": "IC_kwDOCVq1mM5hsyo7",
        "user": {
            "login": "developerChans",
            "id": 68864422,
            "node_id": "MDQ6VXNlcjY4ODY0NDIy",
            "avatar_url": "https://avatars.githubusercontent.com/u/68864422?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/developerChans",
            "html_url": "https://github.com/developerChans",
            "followers_url": "https://api.github.com/users/developerChans/followers",
            "following_url": "https://api.github.com/users/developerChans/following{/other_user}",
            "gists_url": "https://api.github.com/users/developerChans/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/developerChans/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/developerChans/subscriptions",
            "organizations_url": "https://api.github.com/users/developerChans/orgs",
            "repos_url": "https://api.github.com/users/developerChans/repos",
            "events_url": "https://api.github.com/users/developerChans/events{/privacy}",
            "received_events_url": "https://api.github.com/users/developerChans/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-07-18T01:19:29Z",
        "updated_at": "2023-07-18T01:19:49Z",
        "author_association": "NONE",
        "body": "I'm sry.. that's my mistake...\r\n\r\nThe problem was my \"custom_data_transfer\" problem. This error occurred when trying to change \"float data type\" to \"unsigned short data type\" instead of \"unsigned short data type\" in the process.\r\n\r\nIn addition, there was a problem that the CopyTensor did not occur because the Y_shape was transformed before the corresponding CopyTensor occurred.\r\n\r\nHowever, it seems that the flag was incorrectly specified in the process of implementing my SetCustomEP.\r\n\r\nSince this is a resolved issue, I will close the issue.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1639131707/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]