[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1385844730",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14312#issuecomment-1385844730",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14312",
        "id": 1385844730,
        "node_id": "IC_kwDOCVq1mM5Smk_6",
        "user": {
            "login": "shalvamist",
            "id": 94086448,
            "node_id": "U_kgDOBZulMA",
            "avatar_url": "https://avatars.githubusercontent.com/u/94086448?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/shalvamist",
            "html_url": "https://github.com/shalvamist",
            "followers_url": "https://api.github.com/users/shalvamist/followers",
            "following_url": "https://api.github.com/users/shalvamist/following{/other_user}",
            "gists_url": "https://api.github.com/users/shalvamist/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/shalvamist/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/shalvamist/subscriptions",
            "organizations_url": "https://api.github.com/users/shalvamist/orgs",
            "repos_url": "https://api.github.com/users/shalvamist/repos",
            "events_url": "https://api.github.com/users/shalvamist/events{/privacy}",
            "received_events_url": "https://api.github.com/users/shalvamist/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-01-17T18:23:02Z",
        "updated_at": "2023-01-17T23:06:41Z",
        "author_association": "CONTRIBUTOR",
        "body": "Hi Pensarfeo,\r\n\r\nThanks for the detailed report of the issue.\r\nI was able to load the model without issues using the latest version of ORT - 1.13 - \r\n```\r\n<script>\r\n  function importModule(moduleUrl) {\r\n    return new Promise((resolve, reject) => {\r\n      const script = document.createElement('script');\r\n      script.src = moduleUrl;\r\n      script.onload = resolve;\r\n      script.onerror = reject;\r\n      document.head.appendChild(script);\r\n    });\r\n  }\r\n\r\n  async function initOnnxModel() {\r\n    await importModule('https://cdn.jsdelivr.net/npm/onnxruntime-web@1.13/dist/ort.min.js')\r\n    const yolo = await ort.InferenceSession.create('./yolov8m.onnx', { executionProviders: [\"wasm\"] });\r\n  }\r\n  initOnnxModel()\r\n</script>\r\n```\r\nI think the issue you reported was already addressed somewhere between 1.10 & 1.13 releases. Can you please try this code on your end ?\r\n\r\nBTW, the upcoming release will no longer have magic numbers in our exception handling. ORT web will provide error messages.\r\n\r\nThanks,\r\nShalva",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1385844730/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1396718947",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/14312#issuecomment-1396718947",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/14312",
        "id": 1396718947,
        "node_id": "IC_kwDOCVq1mM5TQD1j",
        "user": {
            "login": "Pensarfeo",
            "id": 14980193,
            "node_id": "MDQ6VXNlcjE0OTgwMTkz",
            "avatar_url": "https://avatars.githubusercontent.com/u/14980193?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Pensarfeo",
            "html_url": "https://github.com/Pensarfeo",
            "followers_url": "https://api.github.com/users/Pensarfeo/followers",
            "following_url": "https://api.github.com/users/Pensarfeo/following{/other_user}",
            "gists_url": "https://api.github.com/users/Pensarfeo/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Pensarfeo/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Pensarfeo/subscriptions",
            "organizations_url": "https://api.github.com/users/Pensarfeo/orgs",
            "repos_url": "https://api.github.com/users/Pensarfeo/repos",
            "events_url": "https://api.github.com/users/Pensarfeo/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Pensarfeo/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-01-19T10:04:41Z",
        "updated_at": "2023-01-19T10:04:41Z",
        "author_association": "NONE",
        "body": "@shalvamist Thanks! updating to 1.130 did the trick!",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1396718947/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]