[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/969194282",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-969194282",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/9754",
        "id": 969194282,
        "node_id": "IC_kwDOCVq1mM45xLsq",
        "user": {
            "login": "yuslepukhin",
            "id": 11303988,
            "node_id": "MDQ6VXNlcjExMzAzOTg4",
            "avatar_url": "https://avatars.githubusercontent.com/u/11303988?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yuslepukhin",
            "html_url": "https://github.com/yuslepukhin",
            "followers_url": "https://api.github.com/users/yuslepukhin/followers",
            "following_url": "https://api.github.com/users/yuslepukhin/following{/other_user}",
            "gists_url": "https://api.github.com/users/yuslepukhin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yuslepukhin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yuslepukhin/subscriptions",
            "organizations_url": "https://api.github.com/users/yuslepukhin/orgs",
            "repos_url": "https://api.github.com/users/yuslepukhin/repos",
            "events_url": "https://api.github.com/users/yuslepukhin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yuslepukhin/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-11-15T18:26:23Z",
        "updated_at": "2021-11-15T18:26:23Z",
        "author_association": "MEMBER",
        "body": "I have searched the internet and [this](https://stackoverflow.com/questions/22564780/debugging-ld-inconsistency-detected-by-ld-so) appears to be relevant.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/969194282/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/969196634",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-969196634",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/9754",
        "id": 969196634,
        "node_id": "IC_kwDOCVq1mM45xMRa",
        "user": {
            "login": "yuslepukhin",
            "id": 11303988,
            "node_id": "MDQ6VXNlcjExMzAzOTg4",
            "avatar_url": "https://avatars.githubusercontent.com/u/11303988?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yuslepukhin",
            "html_url": "https://github.com/yuslepukhin",
            "followers_url": "https://api.github.com/users/yuslepukhin/followers",
            "following_url": "https://api.github.com/users/yuslepukhin/following{/other_user}",
            "gists_url": "https://api.github.com/users/yuslepukhin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yuslepukhin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yuslepukhin/subscriptions",
            "organizations_url": "https://api.github.com/users/yuslepukhin/orgs",
            "repos_url": "https://api.github.com/users/yuslepukhin/repos",
            "events_url": "https://api.github.com/users/yuslepukhin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yuslepukhin/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-11-15T18:29:18Z",
        "updated_at": "2021-11-15T18:29:18Z",
        "author_association": "MEMBER",
        "body": "Other results suggest that it may be due to a missing library. For that you would have to use `ldd` to search for libraries dependencies and find out what is missing on the system. Unfortunately, it may be some obscure library.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/969196634/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/970561847",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-970561847",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/9754",
        "id": 970561847,
        "node_id": "IC_kwDOCVq1mM452Zk3",
        "user": {
            "login": "snnn",
            "id": 856316,
            "node_id": "MDQ6VXNlcjg1NjMxNg==",
            "avatar_url": "https://avatars.githubusercontent.com/u/856316?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/snnn",
            "html_url": "https://github.com/snnn",
            "followers_url": "https://api.github.com/users/snnn/followers",
            "following_url": "https://api.github.com/users/snnn/following{/other_user}",
            "gists_url": "https://api.github.com/users/snnn/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/snnn/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/snnn/subscriptions",
            "organizations_url": "https://api.github.com/users/snnn/orgs",
            "repos_url": "https://api.github.com/users/snnn/repos",
            "events_url": "https://api.github.com/users/snnn/events{/privacy}",
            "received_events_url": "https://api.github.com/users/snnn/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-11-16T18:41:46Z",
        "updated_at": "2021-11-16T18:41:46Z",
        "author_association": "MEMBER",
        "body": "It was caused by the patchelf tool we use. \r\nAn alternative solution: Patch https://github.com/pypa/auditwheel, add a custom policy file to whitelist CUDA libraries. Then we can remove our hacks in setup.py. \r\n\r\nThe warnings generated by ldd doesn't impact use, except you can't use ldd with it.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/970561847/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/978198118",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-978198118",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/9754",
        "id": 978198118,
        "node_id": "IC_kwDOCVq1mM46Th5m",
        "user": {
            "login": "adk9",
            "id": 11399,
            "node_id": "MDQ6VXNlcjExMzk5",
            "avatar_url": "https://avatars.githubusercontent.com/u/11399?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/adk9",
            "html_url": "https://github.com/adk9",
            "followers_url": "https://api.github.com/users/adk9/followers",
            "following_url": "https://api.github.com/users/adk9/following{/other_user}",
            "gists_url": "https://api.github.com/users/adk9/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/adk9/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/adk9/subscriptions",
            "organizations_url": "https://api.github.com/users/adk9/orgs",
            "repos_url": "https://api.github.com/users/adk9/repos",
            "events_url": "https://api.github.com/users/adk9/events{/privacy}",
            "received_events_url": "https://api.github.com/users/adk9/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-11-24T20:28:16Z",
        "updated_at": "2021-11-24T20:28:16Z",
        "author_association": "MEMBER",
        "body": "I'm also running into the same issue with onnxruntime-training (1.9.0) and onnxruntime-gpu (1.9.0) wheels installed from PyPI, trying to train a simple model using the CUDA EP. @snnn, the suggested fix above is not clear to me; can you elaborate on it?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/978198118/reactions",
            "total_count": 1,
            "+1": 1,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/978485716",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-978485716",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/9754",
        "id": 978485716,
        "node_id": "IC_kwDOCVq1mM46UoHU",
        "user": {
            "login": "snnn",
            "id": 856316,
            "node_id": "MDQ6VXNlcjg1NjMxNg==",
            "avatar_url": "https://avatars.githubusercontent.com/u/856316?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/snnn",
            "html_url": "https://github.com/snnn",
            "followers_url": "https://api.github.com/users/snnn/followers",
            "following_url": "https://api.github.com/users/snnn/following{/other_user}",
            "gists_url": "https://api.github.com/users/snnn/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/snnn/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/snnn/subscriptions",
            "organizations_url": "https://api.github.com/users/snnn/orgs",
            "repos_url": "https://api.github.com/users/snnn/repos",
            "events_url": "https://api.github.com/users/snnn/events{/privacy}",
            "received_events_url": "https://api.github.com/users/snnn/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-11-24T23:48:39Z",
        "updated_at": "2021-11-24T23:49:22Z",
        "author_association": "MEMBER",
        "body": "First, onnxruntime python packages, \"onnxruntime\" and \"onnxruntime-gpu\", follow manylinux2014([pep-0599](https://www.python.org/dev/peps/pep-0599/) ) standard. But the gpu one, onnxruntime-gpu, isn't fully compliant. \r\n\r\nThe PEP 599 policy says: \"The wheel's binary executables or shared objects may not link against externally-provided libraries except those in the following list\"\r\n\r\n- libgcc_s.so.1\r\n- libstdc++.so.6\r\n- libm.so.6\r\n- libdl.so.2\r\n- librt.so.1\r\n- libc.so.6\r\n- libnsl.so.1\r\n- libutil.so.1\r\n- libpthread.so.0\r\n- libresolv.so.2\r\n- libX11.so.6\r\n- libXext.so.6\r\n- libXrender.so.1\r\n- libICE.so.6\r\n- libSM.so.6\r\n- libGL.so.1\r\n- libgobject-2.0.so.0\r\n- libgthread-2.0.so.0\r\n- libglib-2.0.so.0\r\n\r\nBut we need CUDA. And CUDA isn't in the list. BTW, if you run ldd with onnxruntime's cpu only package, [\"onnxruntime\"](https://pypi.org/project/onnxruntime/), you won't see the error. \r\n\r\nThe policy was designed as any external dependency should be packed into the wheel file. However, we can't. Because,\r\n\r\n1. It will make the package over size. Pypi.org has a 100MB per wheel file size limit.\r\n2. It could cause license issues. I'm not sure if we could redistribute Nvidia's CUDA libraries.\r\n\r\nSo we did a dirty hack.  Before pack the wheel, we patch the so file to pretend it doesn't depend on CUDA. To cheat on manylinux's auditwheel tool. Then we pack the wheel and manually load the CUDA libraries.  The error message you saw is caused the tool for patching *.so files: patchelf. If we don't use the tool, we won't have this issue. \r\n\r\nAlternatively, we could modify the policy. Patch the [auditwheel](https://github.com/pypa/auditwheel) tool, add a custom policy file to whitelist CUDA libraries. The file is: https://github.com/pypa/auditwheel/blob/main/src/auditwheel/policy/manylinux-policy.json . See [#144 ](https://github.com/pypa/auditwheel/issues/144) for more information. \r\n\r\n(Hi @adk9, the above answer is only for onnxruntime inference packages. onnxruntime-training package is built in a special way that I'm not familiar. )\r\n\r\n\r\n\r\n\r\n\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/978485716/reactions",
            "total_count": 1,
            "+1": 1,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1038897255",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-1038897255",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/9754",
        "id": 1038897255,
        "node_id": "IC_kwDOCVq1mM497FBn",
        "user": {
            "login": "GuillaumeTong",
            "id": 38460110,
            "node_id": "MDQ6VXNlcjM4NDYwMTEw",
            "avatar_url": "https://avatars.githubusercontent.com/u/38460110?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/GuillaumeTong",
            "html_url": "https://github.com/GuillaumeTong",
            "followers_url": "https://api.github.com/users/GuillaumeTong/followers",
            "following_url": "https://api.github.com/users/GuillaumeTong/following{/other_user}",
            "gists_url": "https://api.github.com/users/GuillaumeTong/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/GuillaumeTong/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/GuillaumeTong/subscriptions",
            "organizations_url": "https://api.github.com/users/GuillaumeTong/orgs",
            "repos_url": "https://api.github.com/users/GuillaumeTong/repos",
            "events_url": "https://api.github.com/users/GuillaumeTong/events{/privacy}",
            "received_events_url": "https://api.github.com/users/GuillaumeTong/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-02-14T10:11:38Z",
        "updated_at": "2022-02-14T10:11:38Z",
        "author_association": "NONE",
        "body": "Hi @snnn thank you for the detailed explanation of the problem. If I understand correctly, this is basically a problem that stems from not being able to specify CUDA as a pip dependency?\r\n\r\nI am afraid that as a small potato, not familiar with the deeper workings of pip and auditwheel, I am unable to implement the fix you are describing.\r\n\r\nCould the problem be fixed by manually installing a compatible version of CUDA?\r\n\r\nOtherwise, could you give a more line-by line set of instruction on what files to edit and what actions to take after the edit (I take it I need to build the wheel after editing the rules? I have never done that before)?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1038897255/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1039305762",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-1039305762",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/9754",
        "id": 1039305762,
        "node_id": "IC_kwDOCVq1mM498owi",
        "user": {
            "login": "snnn",
            "id": 856316,
            "node_id": "MDQ6VXNlcjg1NjMxNg==",
            "avatar_url": "https://avatars.githubusercontent.com/u/856316?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/snnn",
            "html_url": "https://github.com/snnn",
            "followers_url": "https://api.github.com/users/snnn/followers",
            "following_url": "https://api.github.com/users/snnn/following{/other_user}",
            "gists_url": "https://api.github.com/users/snnn/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/snnn/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/snnn/subscriptions",
            "organizations_url": "https://api.github.com/users/snnn/orgs",
            "repos_url": "https://api.github.com/users/snnn/repos",
            "events_url": "https://api.github.com/users/snnn/events{/privacy}",
            "received_events_url": "https://api.github.com/users/snnn/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-02-14T16:41:58Z",
        "updated_at": "2022-02-14T16:41:58Z",
        "author_association": "MEMBER",
        "body": "> Could the problem be fixed by manually installing a compatible version of CUDA?\r\n\r\nYes. Then ldd will still not work, but the onnxruntime python package should be good.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1039305762/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1039824967",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-1039824967",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/9754",
        "id": 1039824967,
        "node_id": "IC_kwDOCVq1mM49-nhH",
        "user": {
            "login": "GuillaumeTong",
            "id": 38460110,
            "node_id": "MDQ6VXNlcjM4NDYwMTEw",
            "avatar_url": "https://avatars.githubusercontent.com/u/38460110?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/GuillaumeTong",
            "html_url": "https://github.com/GuillaumeTong",
            "followers_url": "https://api.github.com/users/GuillaumeTong/followers",
            "following_url": "https://api.github.com/users/GuillaumeTong/following{/other_user}",
            "gists_url": "https://api.github.com/users/GuillaumeTong/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/GuillaumeTong/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/GuillaumeTong/subscriptions",
            "organizations_url": "https://api.github.com/users/GuillaumeTong/orgs",
            "repos_url": "https://api.github.com/users/GuillaumeTong/repos",
            "events_url": "https://api.github.com/users/GuillaumeTong/events{/privacy}",
            "received_events_url": "https://api.github.com/users/GuillaumeTong/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-02-15T03:49:29Z",
        "updated_at": "2022-02-15T03:50:18Z",
        "author_association": "NONE",
        "body": "In my specific case, after looking at the [onnx runtime requirements](https://onnxruntime.ai/docs/install/#requirements) again, I noticed that I might be missing `cudnn`.\r\nI tried installing [libcudnn8 and libcudnn8-dev](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#package-manager-ubuntu-install), and I was able to run my code successfully. Not quite sure if `libcudnn8-dev` was necessary or if `libcudnn8`  would have been sufficient.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1039824967/reactions",
            "total_count": 2,
            "+1": 2,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1098097912",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-1098097912",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/9754",
        "id": 1098097912,
        "node_id": "IC_kwDOCVq1mM5Bc6T4",
        "user": {
            "login": "VikasOjha666",
            "id": 35727142,
            "node_id": "MDQ6VXNlcjM1NzI3MTQy",
            "avatar_url": "https://avatars.githubusercontent.com/u/35727142?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/VikasOjha666",
            "html_url": "https://github.com/VikasOjha666",
            "followers_url": "https://api.github.com/users/VikasOjha666/followers",
            "following_url": "https://api.github.com/users/VikasOjha666/following{/other_user}",
            "gists_url": "https://api.github.com/users/VikasOjha666/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/VikasOjha666/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/VikasOjha666/subscriptions",
            "organizations_url": "https://api.github.com/users/VikasOjha666/orgs",
            "repos_url": "https://api.github.com/users/VikasOjha666/repos",
            "events_url": "https://api.github.com/users/VikasOjha666/events{/privacy}",
            "received_events_url": "https://api.github.com/users/VikasOjha666/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-04-13T14:09:05Z",
        "updated_at": "2022-04-13T14:32:28Z",
        "author_association": "NONE",
        "body": "@GuillaumeTong @snnn  I am facing the same issue. My cuda version is 10.2 followed the same installation instructions for cudnn for cuda 10.2 still getting the same issue. My OS is Ubuntu 18 on AWS with T4 GPU. What could be the reason?. I also have CUDA 11.6 on my system as well. This problem is arriving in my case with onnxruntime-training installation. Below is the code on execution of which the error is occurring:\r\n\r\nfrom onnxruntime import OrtValue\r\nimport numpy as np\r\nx = OrtValue.ortvalue_from_numpy(np.random.rand(3), 'cuda')\r\n\r\nworks for:\r\nx = OrtValue.ortvalue_from_numpy(np.random.rand(3), 'cpu')",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1098097912/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1098636386",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-1098636386",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/9754",
        "id": 1098636386,
        "node_id": "IC_kwDOCVq1mM5Be9xi",
        "user": {
            "login": "snnn",
            "id": 856316,
            "node_id": "MDQ6VXNlcjg1NjMxNg==",
            "avatar_url": "https://avatars.githubusercontent.com/u/856316?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/snnn",
            "html_url": "https://github.com/snnn",
            "followers_url": "https://api.github.com/users/snnn/followers",
            "following_url": "https://api.github.com/users/snnn/following{/other_user}",
            "gists_url": "https://api.github.com/users/snnn/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/snnn/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/snnn/subscriptions",
            "organizations_url": "https://api.github.com/users/snnn/orgs",
            "repos_url": "https://api.github.com/users/snnn/repos",
            "events_url": "https://api.github.com/users/snnn/events{/privacy}",
            "received_events_url": "https://api.github.com/users/snnn/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-04-14T02:02:41Z",
        "updated_at": "2022-04-14T02:02:41Z",
        "author_association": "MEMBER",
        "body": "I'm not familiar with the onnxruntime-training package. @askhade, could you please help? I think there might be some code in pytorch ran this \"ldd\" command. Do you know how to reproduce it?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1098636386/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1108650893",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-1108650893",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/9754",
        "id": 1108650893,
        "node_id": "IC_kwDOCVq1mM5CFKuN",
        "user": {
            "login": "farzanehnakhaee70",
            "id": 30573681,
            "node_id": "MDQ6VXNlcjMwNTczNjgx",
            "avatar_url": "https://avatars.githubusercontent.com/u/30573681?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/farzanehnakhaee70",
            "html_url": "https://github.com/farzanehnakhaee70",
            "followers_url": "https://api.github.com/users/farzanehnakhaee70/followers",
            "following_url": "https://api.github.com/users/farzanehnakhaee70/following{/other_user}",
            "gists_url": "https://api.github.com/users/farzanehnakhaee70/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/farzanehnakhaee70/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/farzanehnakhaee70/subscriptions",
            "organizations_url": "https://api.github.com/users/farzanehnakhaee70/orgs",
            "repos_url": "https://api.github.com/users/farzanehnakhaee70/repos",
            "events_url": "https://api.github.com/users/farzanehnakhaee70/events{/privacy}",
            "received_events_url": "https://api.github.com/users/farzanehnakhaee70/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-04-25T14:28:26Z",
        "updated_at": "2022-04-25T14:28:26Z",
        "author_association": "NONE",
        "body": "It also solved my issue when upgrading the CUDA to the compatible versions with the onnxruntime-gpu. Thanks a lot.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1108650893/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1124225135",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-1124225135",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/9754",
        "id": 1124225135,
        "node_id": "IC_kwDOCVq1mM5DAlBv",
        "user": {
            "login": "camblomquist",
            "id": 36173306,
            "node_id": "MDQ6VXNlcjM2MTczMzA2",
            "avatar_url": "https://avatars.githubusercontent.com/u/36173306?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/camblomquist",
            "html_url": "https://github.com/camblomquist",
            "followers_url": "https://api.github.com/users/camblomquist/followers",
            "following_url": "https://api.github.com/users/camblomquist/following{/other_user}",
            "gists_url": "https://api.github.com/users/camblomquist/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/camblomquist/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/camblomquist/subscriptions",
            "organizations_url": "https://api.github.com/users/camblomquist/orgs",
            "repos_url": "https://api.github.com/users/camblomquist/repos",
            "events_url": "https://api.github.com/users/camblomquist/events{/privacy}",
            "received_events_url": "https://api.github.com/users/camblomquist/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-05-11T19:50:00Z",
        "updated_at": "2022-05-11T19:50:00Z",
        "author_association": "NONE",
        "body": "I'm in a bit of a similar pickle here, though it might be one outside the scope of this issue or project. Environment includes Ubuntu 18.04, CUDA 11.4, CUDNN 8.2.4, Python 3.6, onnxruntime-gpu coming from pip. I'm packing up the project as a onedir executable using PyInstaller. \r\nOn the build machine, it appears to work as expected. When taking the packaged executable onto a different machine, I get hit with the Inconsistency detected assertion failure. This different machine is also running with CUDA 11.4, but uses a different GPU. For reasons, I'm trying to avoid modifying the system itself on this machine, so it needs to be able to work using the libraries included by PyInstaller.\r\nPyInstaller appears to be properly including all of the relevant CUDA libraries and I've manually specified the inclusion of the onnxruntime_provider_cuda.so and *_shared.so files. For giggles, removing the CUDA libraries from the directory does correctly cause the program to error out due to missing files rather than assertions.\r\nWhen running with `LD_DEBUG=all`, the last line before the assertion fail is `Checking for version 'libcufft.so.10'...` where the rest of it is just specifying that it's required by the onnxruntime_provider library. I don't know if this information is of any use.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1124225135/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1125204290",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-1125204290",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/9754",
        "id": 1125204290,
        "node_id": "IC_kwDOCVq1mM5DEUFC",
        "user": {
            "login": "camblomquist",
            "id": 36173306,
            "node_id": "MDQ6VXNlcjM2MTczMzA2",
            "avatar_url": "https://avatars.githubusercontent.com/u/36173306?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/camblomquist",
            "html_url": "https://github.com/camblomquist",
            "followers_url": "https://api.github.com/users/camblomquist/followers",
            "following_url": "https://api.github.com/users/camblomquist/following{/other_user}",
            "gists_url": "https://api.github.com/users/camblomquist/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/camblomquist/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/camblomquist/subscriptions",
            "organizations_url": "https://api.github.com/users/camblomquist/orgs",
            "repos_url": "https://api.github.com/users/camblomquist/repos",
            "events_url": "https://api.github.com/users/camblomquist/events{/privacy}",
            "received_events_url": "https://api.github.com/users/camblomquist/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-05-12T16:37:14Z",
        "updated_at": "2022-05-12T16:37:14Z",
        "author_association": "NONE",
        "body": "My apologies for the ramble. Desperation tends to do that. I had resolved the issue on my own. It turns out that PyInstaller was not including all of the necessary CUDA libraries. Including them manually allowed onnxruntime to start up (and then crash when it couldn't find the `cudnn_*_infer` libraries, but that error was transparent.)\r\n\r\nI will say though that it is incredibly frustrating to have spent the time on what ended up being a fairly simple issue. I understand that the import hack is done to avoid the eyes of the auditor, but this same hack made it much more difficult to realize that it was just a matter of a missing dependency. I know I'm barking up the wrong tree here since I could've just not used Python, but this type of error would've happened much sooner in the pipeline and likely had a more useful error message in any compiled language.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1125204290/reactions",
            "total_count": 2,
            "+1": 2,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1204905643",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-1204905643",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/9754",
        "id": 1204905643,
        "node_id": "IC_kwDOCVq1mM5H0War",
        "user": {
            "login": "biendltb",
            "id": 5746229,
            "node_id": "MDQ6VXNlcjU3NDYyMjk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/5746229?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/biendltb",
            "html_url": "https://github.com/biendltb",
            "followers_url": "https://api.github.com/users/biendltb/followers",
            "following_url": "https://api.github.com/users/biendltb/following{/other_user}",
            "gists_url": "https://api.github.com/users/biendltb/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/biendltb/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/biendltb/subscriptions",
            "organizations_url": "https://api.github.com/users/biendltb/orgs",
            "repos_url": "https://api.github.com/users/biendltb/repos",
            "events_url": "https://api.github.com/users/biendltb/events{/privacy}",
            "received_events_url": "https://api.github.com/users/biendltb/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-08-04T08:02:02Z",
        "updated_at": "2022-10-10T11:32:16Z",
        "author_association": "NONE",
        "body": "If you are running with `TensorrtExecutionProvider`, reinstall libnvinfer libraries solves the issue in my case:\r\n* Uninstall libnvinfer and tensorrt libraries:\r\n```\r\nsudo apt-get purge \"libnvinfer*\"\r\n```\r\n* Install all libnvinfer libraries (here is the example for cuda-11.4 and libnvinfer 8.2.5.1). Run `apt-cache policy libnvinfer8` to check available versions.\r\n```\r\nsudo apt install libnvinfer8=8.2.5-1+cuda11.4 libnvinfer-plugin8=8.2.5-1+cuda11.4 libnvparsers8=8.2.5-1+cuda11.4 libnvonnxparsers8=8.2.5-1+cuda11.4 libnvinfer-dev=8.2.5-1+cuda11.4 libnvinfer-plugin-dev=8.2.5-1+cuda11.4 libnvparsers-dev=8.2.5-1+cuda11.4 libnvonnxparsers-dev=8.2.5-1+cuda11.4 cuda-cudart-dev-11-4 libcublas-dev-11-4\r\n```\r\nHope it helps.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1204905643/reactions",
            "total_count": 1,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 1,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1271439513",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-1271439513",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/9754",
        "id": 1271439513,
        "node_id": "IC_kwDOCVq1mM5LyKCZ",
        "user": {
            "login": "gorkemgoknar",
            "id": 4275913,
            "node_id": "MDQ6VXNlcjQyNzU5MTM=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4275913?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/gorkemgoknar",
            "html_url": "https://github.com/gorkemgoknar",
            "followers_url": "https://api.github.com/users/gorkemgoknar/followers",
            "following_url": "https://api.github.com/users/gorkemgoknar/following{/other_user}",
            "gists_url": "https://api.github.com/users/gorkemgoknar/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/gorkemgoknar/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/gorkemgoknar/subscriptions",
            "organizations_url": "https://api.github.com/users/gorkemgoknar/orgs",
            "repos_url": "https://api.github.com/users/gorkemgoknar/repos",
            "events_url": "https://api.github.com/users/gorkemgoknar/events{/privacy}",
            "received_events_url": "https://api.github.com/users/gorkemgoknar/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-10-07T10:55:49Z",
        "updated_at": "2022-10-07T10:55:49Z",
        "author_association": "NONE",
        "body": "I hit the similar issue.\r\nApparently you need to use correct onnxruntime-gpu version relevant to your system cuda installation.\r\nI have cuda 10.2 installed, after installing onnxruntime-gpu==1.6 I no longer saw this same error.\r\nOnnxruntime requirements:\r\nhttps://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements\r\n\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1271439513/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]