[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1480718544",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/15171#issuecomment-1480718544",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/15171",
        "id": 1480718544,
        "node_id": "IC_kwDOCVq1mM5YQfjQ",
        "user": {
            "login": "fdwr",
            "id": 1809166,
            "node_id": "MDQ6VXNlcjE4MDkxNjY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1809166?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fdwr",
            "html_url": "https://github.com/fdwr",
            "followers_url": "https://api.github.com/users/fdwr/followers",
            "following_url": "https://api.github.com/users/fdwr/following{/other_user}",
            "gists_url": "https://api.github.com/users/fdwr/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fdwr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fdwr/subscriptions",
            "organizations_url": "https://api.github.com/users/fdwr/orgs",
            "repos_url": "https://api.github.com/users/fdwr/repos",
            "events_url": "https://api.github.com/users/fdwr/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fdwr/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-03-23T07:33:10Z",
        "updated_at": "2023-03-23T07:33:10Z",
        "author_association": "MEMBER",
        "body": "Do you get the same issue with `OrtSessionOptionsAppendExecutionProvider_DML` removed?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1480718544/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1480723930",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/15171#issuecomment-1480723930",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/15171",
        "id": 1480723930,
        "node_id": "IC_kwDOCVq1mM5YQg3a",
        "user": {
            "login": "Maniron28",
            "id": 71628009,
            "node_id": "MDQ6VXNlcjcxNjI4MDA5",
            "avatar_url": "https://avatars.githubusercontent.com/u/71628009?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Maniron28",
            "html_url": "https://github.com/Maniron28",
            "followers_url": "https://api.github.com/users/Maniron28/followers",
            "following_url": "https://api.github.com/users/Maniron28/following{/other_user}",
            "gists_url": "https://api.github.com/users/Maniron28/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Maniron28/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Maniron28/subscriptions",
            "organizations_url": "https://api.github.com/users/Maniron28/orgs",
            "repos_url": "https://api.github.com/users/Maniron28/repos",
            "events_url": "https://api.github.com/users/Maniron28/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Maniron28/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-03-23T07:39:45Z",
        "updated_at": "2023-03-23T07:39:45Z",
        "author_association": "NONE",
        "body": "yes, and I found out that the error was because the \r\n\r\nsFilename = \"C:\\\\Users\\\\Desktop\\\\Image.png\";\r\n\r\n       cv::Mat imageBGR = cv::imread(sFilename);\r\n\r\n         if (imageBGR.empty())\r\n       {\r\n            std::cout << \"Could not open or find the image\" << std::endl;\r\n             return -1;\r\n       }\r\n\r\ncouldnt access the path of the image I am providing and throws the error as mentioned below\r\n       \r\n       error : cv::findDecoder imread_('Could not open or find the image')\r\n\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1480723930/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1482050566",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/15171#issuecomment-1482050566",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/15171",
        "id": 1482050566,
        "node_id": "IC_kwDOCVq1mM5YVkwG",
        "user": {
            "login": "fdwr",
            "id": 1809166,
            "node_id": "MDQ6VXNlcjE4MDkxNjY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1809166?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fdwr",
            "html_url": "https://github.com/fdwr",
            "followers_url": "https://api.github.com/users/fdwr/followers",
            "following_url": "https://api.github.com/users/fdwr/following{/other_user}",
            "gists_url": "https://api.github.com/users/fdwr/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fdwr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fdwr/subscriptions",
            "organizations_url": "https://api.github.com/users/fdwr/orgs",
            "repos_url": "https://api.github.com/users/fdwr/repos",
            "events_url": "https://api.github.com/users/fdwr/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fdwr/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-03-23T23:38:10Z",
        "updated_at": "2023-03-23T23:46:50Z",
        "author_association": "MEMBER",
        "body": "> yes, and I found out that the error\r\n\r\nGood that you found it. Is the issue closeable now then?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1482050566/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1482237585",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/15171#issuecomment-1482237585",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/15171",
        "id": 1482237585,
        "node_id": "IC_kwDOCVq1mM5YWSaR",
        "user": {
            "login": "Maniron28",
            "id": 71628009,
            "node_id": "MDQ6VXNlcjcxNjI4MDA5",
            "avatar_url": "https://avatars.githubusercontent.com/u/71628009?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Maniron28",
            "html_url": "https://github.com/Maniron28",
            "followers_url": "https://api.github.com/users/Maniron28/followers",
            "following_url": "https://api.github.com/users/Maniron28/following{/other_user}",
            "gists_url": "https://api.github.com/users/Maniron28/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Maniron28/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Maniron28/subscriptions",
            "organizations_url": "https://api.github.com/users/Maniron28/orgs",
            "repos_url": "https://api.github.com/users/Maniron28/repos",
            "events_url": "https://api.github.com/users/Maniron28/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Maniron28/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-03-24T04:36:12Z",
        "updated_at": "2023-03-24T04:36:31Z",
        "author_association": "NONE",
        "body": "> > yes, and I found out that the error\r\n> \r\n> Good that you found it. Is the issue closeable now then?\r\n\r\nNot yet, Now I am facing a issue which I have mentioned in the https://github.com/microsoft/onnxruntime/issues/15171#issuecomment-1480723930",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1482237585/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]